### ISSUE TITLE
model castorini/LiT5-Distill-large is 404

### ISSUE THREAD

**Issue by stanpcf** [castorini/LiT5-Reranking#1]
great work for rerank!!!
I found model `castorini/LiT5-Distill-large` which in the readme is 404. is there plan-time to release the model.

**Comment by ronakice** [comment]
`castorini/LiT5-Distill-large` is out here - https://huggingface.co/castorini/LiT5-Distill-large/tree/main

Stay tuned for more information tomorrow!

**Comment by manveertamber** [comment]
We have released all the models in [https://huggingface.co/castorini/](https://huggingface.co/castorini/)
and the paper too: [[2312.16098] Scaling Down, LiTting Up: Efficient Zero-Shot Listwise Reranking with Seq2seq Encoder-Decoder Models](https://arxiv.org/abs/2312.16098)
