### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by bclavie** [castorini/LiT5-Reranking#2]
Hey @manveertamber!

I'm planning on implementing LiT5 into the `rerankers` (https://github.com/answerdotai/rerankers) library in the near future. Whenever possible, I prefer to err on the side of re-using official implementations, to make sure the results aren't badly representing any given method.

I was wondering, since this repo doesn't have a licence, do you consider the code in it re-usable (with due credit given of course)? If so, would you be willing to consider adding a permissive licence such as MIT or Apache 2.0 to reflect thus?

Thanks a lot, and congrats on the great work!

**Comment by manveertamber** [comment]
Hi @bclavie,

Happy to see your interest in our work! Absolutely, I've added an Apache 2.0 license. 

Best of luck with your implementation!

**Comment by bclavie** [comment]
> Hi @bclavie,
> 
> Happy to see your interest in our work! Absolutely, I've added an Apache 2.0 license.
> 
> Best of luck with your implementation!

Perfect, thank you! I'll try and get that integrated soon!
